### ISSUE TITLE
Choose names and thumbnails for animations

### ISSUE THREAD

**Issue by sadaffgh** [sadaffgh/Hackathon#8]
**To-Do:**

- [x] come up with various names
- [x] come up / choose various thumbnails
- [x] Short introduction for each ticket
