### ISSUE TITLE
Implement the whole storyline

### ISSUE THREAD

**Issue by sadaffgh** [sadaffgh/Hackathon#9]
**To-Do:**

- [ ] Storyline: "Happy turtle family"
- [ ] Storyline: "Turtle siblings playing"
- [ ] Storyline: "Plastic object falling"
- [ ] Storyline: "Baby turtle eats plastic"
- [ ] Storyline: "Baby turtle gets sick"
- [ ] Storyline: "Siblings go to mummy turtle"
- [ ] Storyline: "Mom explains what to do"
- [ ] Storyline: "Baby turtle gets well"
- [ ] Storyline: "Siblings playing happily"
